version: '3.8'
services:
  data_ingestion_service:
    build:
      context: ./../data-ingestion-cp
    environment:
      - TRAININGDB_API=http://trainingdb_service:5001/training-db/rawdata
    depends_on:
      - trainingdb_service
    networks:
      - training-pipeline
    ports:
      - "5000:5000"
  trainingdb_service:
    build:
      context: ./../trainingdb-postgres-cp
    environment:
      - DB_URL=postgresql://testuser:testpass@pgdb_server:5432/features
    depends_on:
      - pgdb_server
    networks:
      - training-pipeline
    ports:
      - "5001:5000"
  pgdb_server:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    networks:
      - training-pipeline
    ports:
      - "5432:5432"
    volumes:
      - /home/y_huang_15/pgdata:/var/lib/postgresql/data
  db_admin:
    image: adminer
    restart: always
    networks:
      - training-pipeline
    ports:
      - "8080:8080"
networks:
  training-pipeline:
